[package]
name = "ziouring"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.19.0"
jni-sys = "0.3.0"
io-uring = "0.5"
